name: pokemon_go
description: PokemonGO app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  json_annotation: ^4.6.0
  http: ^0.13.4
  get: ^4.6.1
  swipe: ^0.0.1
  flutter_screenutil: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: RobotoBold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
